CREATE TABLE board
(
	NO VARCHAR2(4) NOT NULL,
	title VARCHAR2(30) NOT NULL,
	content VARCHAR2(255) NOT NULL,
	writer VARCHAR2(10) NOT NULL,
	writeDate TIMESTAMP NOT NULL,
	hit NUMBER(4) NOT NULL,
	CONSTRAINT PK_board PRIMARY KEY (NO)
);

COMMENT ON TABLE BOARD.BOARD IS '게시글 저장 테이블';
COMMENT ON COLUMN BOARD.BOARD."NO" IS '순번';
COMMENT ON COLUMN BOARD.BOARD.TITLE IS '제목';
COMMENT ON COLUMN BOARD.BOARD.CONTENT IS '내용';
COMMENT ON COLUMN BOARD.BOARD.WRITER IS '작성자';
COMMENT ON COLUMN BOARD.BOARD.WRITEDATE IS '작성일';
COMMENT ON COLUMN BOARD.BOARD.HIT IS '조회수';
